CREATE DATABASE WAY;
USE WAY;
CREATE TABLE VIEW(
EMP_ID INT,
NAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY INT);
INSERT INTO VIEW(EMP_ID,NAME,DEPARTMENT,SALARY)value
(1,"ALICE","HR",50000),
(2,"BOB","IT",70000),
(3,"CHARLIE","IT",60000),
(4,"DAVID","HR",55000),
(5,"EVE","FINANCE",65000);

#1 WRITE A CTE TO RANK EMPLOYEES WITHIN EACH DEPARTMENT BY SALARY(HIGHEST TO LOWEST)

WITH RANKED EMPS AS(
SELECT*,
RANK()
