#CREATE A TRIGGER THAT UPDATES AN INVENTORY TABLE WHENEVER A NEW SALE IS RECORDED IN THE SALE TABLE. SPECIFICALLY WHEN A NEW SALE IS INSERTED INTO THE SALES TABLE,THE TRIGGER SHOULD DECREASES THE QUANTITY OF THE CORRESPONDINGPRODUCT IN THE INVENTORY TABLE

CREATE DATABASE VIEW;
CREATE TABLE INVENTORY(
PRODUCT_ID INT PRIMARY KEY,
PRODUCT_NAME VARCHAR(100),
QUANTITY INT);

CREATE TABLE SALES(
SALE_ID INT AUTO_INCREMENT PRIMARY KEY,
PRODUCT_ID INT,
AMOUNT DECIMAL(10,2),
SALE_DATE DATE,
QUANTITY_SOLD INT);

#2 INSERT SAMPLE DATA INTO THE INVENTORY TABLE

INSERT INTO INVENTORY(PRODUCT_ID,PRODUCT_NAME,QUANTITY)VALUES
(1,'PRODUCT A',100),
(2,'PRODUCT B',150),
(3,'PRODUCT C',200);

#3CREATE THE TRIGGER
DELIMITER //
CREATE TRIGGER AFTER_SALES_INSERT
AFTER INSERT  ON SALES
FOR EACH ROW
BEGIN
UPDATE INVENTORY
SET QUANTITY = QUANTITY - NEW.QUANTITY_SOLD
WHERE PRODUCT_ID=NEW.PRODUCT_ID;
END //
DELIMITER ;

#4 INSERT A NEW SALE TO TEST THE TRIGGER
INSERT INTO SALES(PRODUCT_ID,AMOUNT,SALE_DATE,QUANTITY_SOLD)VALUE
(1, 50.00,'2024-07-01' , 10);
INSERT INTO SALES(PRODUCT_ID,AMOUNT,SALE_DATE,QUANTITY_SOLD)VALUE
(2, 50.00,'2024-08-01' , 50);

#5 CHECK THE INVENTORY TABLE TO SEE THE RESULT
SELECT*FROM INVENTORY;
SHOW TRIGGERS;
#6DROP THE TRIGGER IF NEEDED
DROP TRIGGER IF EXISTS AFTER_SALES_INSERT;
SHOW TRIGGERS;


#DELETE TRIGGER
CREATE TABLE EMPLOYEES(
EMP_ID INT PRIMARY KEY,
NAME VARCHAR(100),
DEPARTMENT VARCHAR(50));
CREATE TABLE DELETED_EMPLOYEES_LOG(
LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
EMP_ID INT,
NAME VARCHAR(100),
DEPARTMENT VARCHAR(50),
DELETED_AT DATETIME);

DELIMITER //
CREATE TRIGGER AFTER_EMPLOYEES_DELETE
AFTER DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
INSERT INTO DELETED_EMPLOYEES_LOG(EMP_ID,NAME,DEPARTMENT,DELETED_AT)
VALUES(OLD.EMP_ID,OLD.NAME,OLD.DEPARTMENT,NOW());
END //
DELIMITER ;

INSERT INTO EMPLOYEES(EMP_ID,NAME,DEPARTMENT)VALUES
(1,'ALICE','HR'),
(2,'BOB','IT'),
(3,'CHARLIE','FINANCE');
SELECT*FROM EMPLOYEES;

DELETE FROM EMPLOYEES WHERE EMP_ID=2;
SELECT*FROM DELETED_EMPLOYEES_LOG;

